feat: add `FetchAccountService`
pulsate-dev/pulsate pull request #113
Opened 2023-12-15 12:45 UTC by m1sk9

## What does this PR do?

Add `FetchAccountService`. 

This service allows you to get an account from account name.

2023-12-15 13:26 UTC, laminne requested changes
気になるところがありました

2023-12-15 13:26 UTC, laminne commented on pkg/accounts/service/fetchAccount.test.ts
> +  name: 'john_doe@example.com',
```suggestion
  name: '@john_doe@example.com',
```
nameの仕様はこうです.

2023-12-15 13:26 UTC, laminne commented on pkg/accounts/service/fetchAccount.test.ts
> +  const res = await registerService.handle(
[must]
ここで`registerService`を使う意味はないと思います.  
このテストは`fetchAccountService`の動作を確認するためにあるので,
ダミーのレポジトリを直接編集するべきです.

2023-12-15 13:26 UTC, laminne commented on pkg/accounts/service/fetchAccount.ts
> +    }
こうした方がいいと思います(このままでは無意味な`try-catch`になってしまう).
```suggestion
    try {
      const account = Option.unwrap(res);
      return Result.ok(account);
    } catch (e) {
      return Result.err(e);
    }
```

2023-12-15 13:38 UTC, laminne commented on pkg/accounts/service/fetchAccount.test.ts
> +  name: 'john_doe@example.com',
nameって不変な変数で、setterが無いのでテストが書けないのです.  
`new()`が呼ばれたときにバリデーションを行うというやり方もあるとは思いますが...

2023-12-15 13:42 UTC, m1sk9 commented on pkg/accounts/service/fetchAccount.test.ts
> +  name: 'john_doe@example.com',
Fixed https://github.com/pulsate-dev/pulsate/pull/113/commits/363f5471a74196ac78080d898584c47f57f1686d

2023-12-15 13:50 UTC, m1sk9 commented on pkg/accounts/service/fetchAccount.test.ts
> +  const res = await registerService.handle(
`registerService` を使うような作り方を共通化しようみたいな話ありませんでしたか?

2023-12-15 13:51 UTC, laminne commented on pkg/accounts/service/fetchAccount.test.ts
> +  const res = await registerService.handle(
そんな話があった気がする

2024-02-07 17:45 UTC, m1sk9 commented on pkg/accounts/service/fetchAccount.test.ts
> +  const res = await registerService.handle(
Fixed https://github.com/pulsate-dev/pulsate/pull/113/commits/54a26df2d01cbe3bb11b75c42b478190c2c8d078

2024-02-08 00:04 UTC, laminne requested changes
同じ内容で2点直して欲しいところがありました

2024-02-08 00:04 UTC, laminne commented on pkg/accounts/service/fetchAccount.test.ts
> +    repository.reset();
`repository.reset`は`describe`スコープで`afterEach`から呼び出すようにしてほしいです

2024-02-08 00:04 UTC, laminne commented on pkg/accounts/service/fetchAccount.test.ts
> +    repository.reset();
こちらも同様です

2024-02-08 00:32 UTC, m1sk9 commented on pkg/accounts/service/fetchAccount.test.ts
> +    repository.reset();
Fixed https://github.com/pulsate-dev/pulsate/pull/113/commits/0be283ae0d4b973c6c0ad3b18d3a54dc541498c2

2024-02-08 00:32 UTC, m1sk9 commented on pkg/accounts/service/fetchAccount.test.ts
> +    repository.reset();
Fixed https://github.com/pulsate-dev/pulsate/pull/113/commits/0be283ae0d4b973c6c0ad3b18d3a54dc541498c2

2024-02-08 00:34 UTC, laminne approved these changes
あっぷるーゔ

2024-02-08 00:34 UTC, merged