feat: impl AuthenticationService
pulsate-dev/pulsate pull request #118
Opened 2024-02-07 14:33 UTC by laminne

## What does this PR do?
パスワード認証サービスの実装

## Additional information

2024-02-07 14:45 UTC, MikuroXina requested changes

2024-02-07 14:45 UTC, MikuroXina commented on pkg/accounts/service/authenticate.test.ts
> +      passwordEncoder: new Argon2idPasswordEncoder(),
```suggestion
      passwordEncoder: encoder,
```
13 行目の `encoder` は使わないのでしょうか

2024-02-07 14:45 UTC, MikuroXina commented on pkg/accounts/service/authenticate.ts
> +  private readonly EPOCH = 1640995200000;
マジックナンバーになっているので, クラス外の定数に分けておいて, 具体的な定数名あるいは値の意味についてのコメントを付けて欲しいです.
またそうなると, この定数はトークンのモデルと密接に関わるので, `TokenPair` とあわせて `model` フォルダ内のファイルへ移動させるのもよいかもしれません.

2024-02-07 14:45 UTC, MikuroXina commented on pkg/accounts/service/tokenGenerator.ts
> +    expiredAt: number,
`Date` が `number` になったことで期待される数値の意味が引数名から読み取れなくなったのは, あまり良くないように思います. 単位やエポックを規定した時刻の型を, `model` 内で公称型として定義したほうがよさそうです.

2024-02-07 14:57 UTC, laminne commented on pkg/accounts/service/authenticate.ts
> +  private readonly EPOCH = 1640995200000;
EPOCHはモジュールごとに定義するものではなくシステム全体で使用するものですが、`pkg/account`以外の場所に定義すべきと思うのですがどう思われますか？
(EPOCH以外にも時刻操作系関数などをまとめておきたい気持ちがあります)

2024-02-07 15:01 UTC, MikuroXina commented on pkg/accounts/service/authenticate.ts
> +  private readonly EPOCH = 1640995200000;
検索してみると `pkg/id/mod.ts` にも同様のコードがありましたので, 私は新しく `pkg/time` を設けて時刻操作をまとめたほうがいいかと思います.

2024-02-07 15:01 UTC, laminne commented on pkg/accounts/service/authenticate.ts
> +  private readonly EPOCH = 1640995200000;
その方針で実装してみようと思います.

2024-02-07 15:56 UTC, MikuroXina requested changes

2024-02-07 15:56 UTC, MikuroXina commented on pkg/accounts/service/tokenGenerator.test.ts
> +      calculateDiffFromEpoch(new Date('2099/12/31 12:59:59')),
```suggestion
      calculateDiffFromEpoch(new Date('2099-12-31T12:59:59Z')),
```
この `/` で区切る書き方は処理系によって動かない書き方なので, ISO 8601 ライクの書き方にしたほうがいいと思います. この後の 26, 27 行目なども同様です.

2024-02-07 15:56 UTC, MikuroXina commented on pkg/time/mod.ts
> +};
```suggestion
declare const pulsateTime: unique symbol;
export type PulsateTime = number & {
  [pulsateTime]: never;
};
```
公称型にするためのフィールドの値に意味はないので, `never` にしておいてもよいかと思います. また型としては UNIX エポックではないので, UNIX の名前が含まれるのはよくないと思います.

2024-02-07 15:56 UTC, MikuroXina commented on pkg/time/mod.ts
> +export const EPOCH = 1640995200000n;
UNIX エポックと Pulsate エポックのミリ秒単位の差がこうなるということをコメントに残してはどうでしょうか

2024-02-07 16:51 UTC, m1sk9 requested changes

2024-02-07 16:51 UTC, m1sk9 commented on pkg/id/mod.ts
>      const time = this.clock.Now();
IMO:

変数名, `time` より `now` のほうが適切なのでは?

2024-02-08 05:09 UTC, laminne commented on pkg/time/mod.ts
> +export const EPOCH = 1640995200000n;
`1640995200000n`は`2022-01-01T00:00:00.000Z`なのでUNIX EpochとPulsate Epochの差ではないです.

2024-02-08 05:13 UTC, m1sk9 approved these changes
私からは以上です. LGTM

2024-02-08 10:19 UTC, MikuroXina commented on pkg/time/mod.ts
> +export const EPOCH = 1640995200000n;
すいません, ちょっと言葉足らずだったかもしれません. エポックというのは計算の基準に用いる特定の時刻のことで, それ自体は整数ではなく年月日時分秒で表すもののはずです. ですのでエポックと称して整数が割り当てられているのは直感的におかしいのではないかと思いました.
`Date` コンストラクタの数値表現では, ECMAScript エポック (UNIX エポックと同じ) からのミリ秒数を扱っています. しかし私たちは Pulsate エポック (`2022-01-01T00:00:0.000Z`) からのミリ秒数を用いて計算する場面があるわけです.
ここで登場している `1640995200000n` はこれら 2 つのエポックの時差を補正するために足すミリ秒数単位の定数ですので, コメントの記述あるいは `EPOCH` と称するのはおかしいでしょうという話をしたかったのです.

2024-02-08 14:06 UTC, laminne commented on pkg/time/mod.ts
> +export const EPOCH = 1640995200000n;
`OffsetFromUnixEpoch`と命名しました

2024-02-08 14:19 UTC, MikuroXina approved these changes

2024-02-08 14:19 UTC, MikuroXina commented on pkg/accounts/service/authenticate.test.ts
> +    ).toBe(true);
```suggestion
    const result = Result.unwrap(await service.handle(
      '@test@example.com',
      'じゃすた・いぐざんぽぅ',
    ));
    expect(
      await tokenGenerator.verify(result.authorizationToken),
    ).toBe(true);
    expect(
      await tokenGenerator.verify(result.refreshToken),
    ).toBe(true);
```
まとめて `unwrap` したほうがきれいになると思います

2024-02-08 14:23 UTC, merged