feat: Add InactiveAccount Model
pulsate-dev/pulsate pull request #135
Opened 2024-02-16 23:42 UTC by aqyuki

## What does this PR do?

- [ ] 不活性な状態のアカウントを表すモデルである，`InactiveAccount`の追加．
- [ ] InactiveAccountをAccountに変化させるためのメソッドの追加
- [ ] InactiveAccountのリポジトリの追加
- [ ] スキーマのマイグレーション
- [ ] AccountからInactiveAccountに関連する処理の削除

## Additional information

2024-02-16 23:56 UTC, aqyuki commented
a4012a9 でコメントアウトした行は本来望まれる動作としてはAccountStatusが`active`になるべきだが現在のAccountのファクトリー関数の仕様上`notActivated`になるためコメントアウトしている．
AccountStatusが削除されると関連するサービスの修正も必要となるのでひとまずコメントアウトし後で修正・削除する．

2024-02-17 06:56 UTC, laminne requested changes

2024-02-17 06:56 UTC, laminne commented on pkg/accounts/model/inactiveAccount.test.ts
> +    // expect(account.getStatus).toBe('active'); NOTE: This line will be removed when account status was removed.
不要なら消してよいのでは?

2024-02-17 08:55 UTC, aqyuki commented on pkg/accounts/model/inactiveAccount.test.ts
> +    // expect(account.getStatus).toBe('active'); NOTE: This line will be removed when account status was removed.
e69a058 で削除しました

2024-02-20 12:54 UTC, laminne requested changes

2024-02-20 12:54 UTC, laminne commented on pkg/accounts/model/inactiveAccount.ts
> +    this.activated = arg.activated;
アクティブかというのは自明であると思いますので、受け取る必要はないと思いますがどうですか？

2024-02-21 11:41 UTC, laminne reviewed
updatedAtやdeletedAtを`Option<Date>`にすることを検討してみてください

2024-02-21 11:48 UTC, aqyuki commented
> updatedAtやdeletedAtを`Option<Date>`にすることを検討してみてください

InactiveAccountsの中にはupdatedAtやdeletedAtの定義が含まれていないため，スコープ外だとおもいます．

2024-02-21 11:50 UTC, laminne approved these changes
単なるミスでした.
Approve

2024-02-21 11:52 UTC, merged