feat: add mock for Clock interface
pulsate-dev/pulsate pull request #162
Opened 2024-02-26 13:06 UTC by aqyuki

## What does this PR do?

Add mock for Clock interface and change to use MockClock when testing

2024-02-26 14:05 UTC, MikuroXina requested changes

2024-02-26 14:05 UTC, MikuroXina commented on pkg/accounts/service/accountVerifyToken.test.ts
> +const mockClock = new MockClock(new Date('2023/9/10 00:00:00 UTC'));
```suggestion
const mockClock = new MockClock(new Date('2023-09-10T00:00:00Z'));
```
この日付形式は処理系依存なので, ISO 8601 拡張形式にしておきたいです. 他も同様です.

2024-02-27 03:12 UTC, MikuroXina approved these changes

2024-02-27 03:14 UTC, laminne approved these changes

2024-02-27 03:14 UTC, merged