chore: replace `build` script
pulsate-dev/pulsate pull request #228
Opened 2024-03-24 09:29 UTC by Nanai10a

## What does this PR do?

`package.json` の `build` スクリプトの置き換えを行います.

## Additional information

- 旧 `build` スクリプトを `check` として残してあります
- 中括弧展開構文を使っているので bash 以外の環境下で動作するか不明です
  - glob 展開は esbuild が行っています

2024-03-24 09:33 UTC, laminne requested changes

2024-03-24 09:33 UTC, laminne commented on package.json
> +    "check": "tsc -p .",
型チェックだけなら`--noEmit`をつけるべきかと.
```suggestion
    "check": "tsc --noEmit -p .",
```

2024-03-24 10:30 UTC, m1sk9 commented
> 中括弧展開構文を使っているので bash 以外の環境下で動作するか不明です 
Fish で動くことを確認しました.
Windows (PowerShell) での動作が保証できないのであれば CONTRIBUTING.md などに書き残しておく必要があるかもしれない?

2024-03-24 14:07 UTC, Nanai10a commented on package.json
> +    "check": "tsc -p .",
fdeafe8dbca9deba07918d6d33f835fcd917d824 で対応しました.

2024-03-24 14:12 UTC, laminne approved these changes

2024-03-24 14:44 UTC, Nanai10a commented
超簡潔にですが, build script を組んでみました… シェル非依存での glob 展開をするならこういう事にもなり得ると思うのですが, その点どう思われますか. そこまでする必要はないでしょうか.

```js
// use with `node build.js -- **/*.ts`
import { build } from 'esbuild';
import { glob } from 'glob';

const args = process.argv.filter((g, _, aThis) => {
  if (aThis.isIgnored) {
    return true;
  }

  if (g === '--') {
    aThis.isIgnored = true;
  }

  return false;
});

glob(args, { ignore: 'node_modules/*' })
  .then((paths) =>
    build({
      entryPoints: paths,
      platform: 'node',
      outdir: './build',
      sourcemap: 'external',
    }),
  )
  .then((res) => {
    res.errors.forEach((m) => console.log(`error: ${m}`));
    res.warnings.forEach((m) => console.log(`warning: ${m}`));

    console.log(
      (res.errors.length === 0 ? 'No' : res.errors.length) +
        ' errors, ' +
        (res.warnings.length === 0 ? 'No' : res.warnings.length) +
        ' warnings emitted',
    );
  });
```

---

足りていない挙動:
- `.gitignore` の適用
  - `node_modules/*` を無視することで部分的に再現
- ビルド結果出力の最適化
- `require('node:path').sep` を使ってない

2024-03-25 04:43 UTC, m1sk9 commented
あまりスクリプトを増やしたくないというのは私個人の意見です. (それを保守するのに時間をかけたくない)
特定のシェルに依存したくないのも本心なのでそれ以外の方法がなければ採用してもいいと思います.

2024-03-25 18:08 UTC, Nanai10a commented on build.js
> +/* global console, process */
これで良いのだろうか？
ref. [`no-undef`](https://eslint.org/docs/latest/rules/no-undef)

2024-03-26 13:16 UTC, Nanai10a commented on build.js
> +/* global console, process */
結論: 良くない

2024-03-26 13:28 UTC, laminne approved these changes

2024-03-26 13:29 UTC, merged