DUMP CODES
pulsate-dev/pulsate pull request #239
Opened 2024-03-28 02:31 UTC by Nanai10a

## What does this PR do?

NONWRITTEN

## Additional information

NONWRITTEN

- 先頭のコミットは消し飛びます

2024-03-28 03:12 UTC, laminne requested changes

2024-03-28 03:12 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    private readonly fetchNoteService: FetchNoteService,
これらはintermoduleモジュールからimportしたものを使ってください

2024-03-28 03:12 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +          : panic();
throwするよりResult.errを返した方が良いかと

2024-03-28 03:12 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    .regex(/^\d{64}$/)
Pulsate-SnowflakeIDは固定長ではないのでこれは落ちると思います

2024-03-28 03:23 UTC, Nanai10a commented on pkg/notes/model/repository.ts
> +  | { type: 'updated'; less: Date }
如何なるタイムラインでも更新日時は並び順に一切考慮されない (考慮されるのは投稿日時のみ) ということで良いですよね？

2024-03-28 03:30 UTC, Nanai10a commented on pkg/notes/model/repository.ts
> +  | { type: 'author'; any: ID<AccountID>[] }
ここでは投稿者で投稿をフィルタしているので, タイムラインに流す投稿は **指定したアカウントがフォローしているアカウント全ての投稿** に絞る, という手法を取っています. 指定したアカウントとは, つまり `/timeline/home` では認証情報の主であり, `/timeline/accounts/:spec` では `:spec` が該当し, `/timeline/global` は フィルタ無し (全投稿者による投稿の集合) となります.

2024-03-28 03:34 UTC, Nanai10a commented on pkg/timeline/adaptor/controller/timeline.ts
> +    private readonly fetchNoteService: FetchNoteService,
`AccountModule` は既にあるものを (必要に応じて) 拡張するとして, `NoteModule` は別で立てる必要がありますね？

2024-03-28 03:42 UTC, Nanai10a commented on pkg/timeline/adaptor/controller/timeline.ts
> +    .regex(/^\d{64}$/)
Zod によるパーサ (少なくとも型判定ができるもの) が欲しいのですが, 少なくとも `ID<T>` と `AccountName` のパーサが欲しいのですが, 既知の実装か formal な規格が存在しますか？

2024-03-28 03:47 UTC, Nanai10a commented on pkg/notes/model/repository.ts
> +  | { type: 'cw'; is: string }
主題から少し逸れますが, "contents warning comment" はどのように表記するのが正解なのでしょうか？ CwComment のような略も存在していたと思いますが, ここでは "CW(C)" と頭文字まで切り詰めています. ~~というかそもそも少し長すぎやしませんか？より簡潔な表現があると良いような…~~

2024-03-28 03:49 UTC, laminne commented on pkg/notes/model/repository.ts
> +  | { type: 'updated'; less: Date }
Yes, 現時点ではそうです

2024-03-28 03:50 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    private readonly fetchNoteService: FetchNoteService,
そうしてください

2024-03-28 03:52 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    .regex(/^\d{64}$/)
どちらも既知の実装はありません

2024-03-28 04:13 UTC, Nanai10a commented on pkg/timeline/adaptor/controller/timeline.ts
> +    .regex(/^\d{64}$/)
`ID<T>` に関して了解しました. `AccountName` に関して該当する仕様が見つけられなかったのですが, ご教示願えますでしょうか？

2024-03-28 04:19 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    .regex(/^\d{64}$/)
Notionに記載があります

2024-07-21 10:19 UTC, laminne commented
#428 で実装済み

2024-07-21 10:19 UTC, closed without merging