feat: add zod schema of domain primitives
pulsate-dev/pulsate pull request #244
Opened 2024-03-29 10:44 UTC by Nanai10a

## What does this PR do?

`ID<T>` と `AccountName` への Zod schema を提供します.

## Additional information

- 多分大丈夫だと思います
- テストケース他に提供あれば教えてください

2024-03-29 11:13 UTC, MikuroXina requested changes

2024-03-29 11:13 UTC, MikuroXina commented on pkg/id/mod.ts
> +      );
```suggestion
      try {
        const n = BigInt(s);
        return (
          n >= 0b1111111111111111111111n &&
          n <= 0b1111111111111111111111111111111111111111111111111111111111111111n
        );
      } catch {
        return false;
      }
```
無理に `let` で外に出さなくても, これでどうでしょう

2024-03-29 11:13 UTC, MikuroXina commented on pkg/id/mod.test.ts
> +  });
せっかくなら ID を長くし過ぎるテストケースも用意したいです.

2024-03-29 11:25 UTC, Nanai10a commented on pkg/id/mod.ts
> +      );
3e8560162f51905bcbbad6e8a4a7e5874b59c113 で対応しました.

2024-03-29 11:26 UTC, Nanai10a commented on pkg/id/mod.test.ts
> +  });
385b2acdff773229a7576e150d1756c610331c8e で対応してみましたが, これでどうでしょう？

2024-03-29 13:26 UTC, laminne requested changes

2024-03-30 00:46 UTC, Nanai10a commented on pkg/accounts/model/account.test.ts
> +    expect(check('@日本語example.com')).toBe(false);
8e8984a265c6902307e885fe861478bff0915956 で対応しました. ただこれ, 単純にスキームが間違ってるだけなので当然落ちていたのですが, 正規化されていないドメインを弾くという意味で少し修正してそのまま残してあります. 逆に正規化されたドメインであれば通ることも検証しています.

2024-03-30 01:00 UTC, MikuroXina approved these changes

2024-03-31 09:42 UTC, laminne requested changes

2024-03-31 09:42 UTC, laminne commented on pkg/accounts/model/account.ts
> +  .regex(/^@([a-zA-Z\d][\w\-.]*)@(([\w\-~.!$&'()*+,;=]|(%[\dA-F]{2}))+)$/)
`&`などは使用不可な気がします.  
((正規表現が複雑なのでコメントを書くべきだと思います

2024-03-31 22:52 UTC, MikuroXina requested changes

2024-03-31 22:52 UTC, MikuroXina commented on pkg/accounts/model/account.ts
> +    const parts = s.split('@', 3);
```suggestion
    const parts = s.split('@');
```
分割数に制限をかけると, `"@hoge@example.com@false"` のようなパターンでも検査に通過してしまうと思います. こちらのような文字列もテストケースに追加しておいてください.

2024-03-31 22:52 UTC, MikuroXina commented on pkg/accounts/model/account.ts
> +      if (!/^[a-zA-Z](?:.*[a-zA-Z0-9])?$/.test(label)) {
```suggestion
      if (!/^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(label)) {
```
RFC を読む限りだとこういう定義になっているかと

2024-04-03 23:28 UTC, Nanai10a commented on pkg/accounts/model/account.ts
> +      if (!/^[a-zA-Z](?:.*[a-zA-Z0-9])?$/.test(label)) {
```ts
    // ref. RFC1035 https://www.rfc-editor.org/rfc/rfc1035#page-8
    //
    // check. ドメイン名は RFC1035 より "<subdomain>" を参照, 空白は許容しない
    //        ここでは文字種の検証のみ
    if (!/^[a-zA-Z0-9\-.]+$/.test(domain)) {
      return false;
    }
```
ここで文字種に関する識別は済ませているつもりですが, 2 重チェックにしようと思います

2024-04-03 23:31 UTC, Nanai10a commented on pkg/accounts/model/account.ts
> +      if (!/^[a-zA-Z](?:.*[a-zA-Z0-9])?$/.test(label)) {
2a453ca9f331a6df1cabae31eac2d2c242cec45c で対応しました.

2024-04-04 04:20 UTC, MikuroXina requested changes

2024-04-04 16:36 UTC, Nanai10a commented on pkg/accounts/model/account.test.ts
6c52ae14ea5fdf0c31abe66ae7ff309ebb8982b9 で対応しました.

2024-04-05 12:45 UTC, laminne requested changes

2024-04-05 12:45 UTC, laminne commented on pkg/id/mod.test.ts
> +    expect(check('0')).toBe(false);
`0`というIDは仕様上生成されうるかと

2024-04-05 14:41 UTC, Nanai10a commented on pkg/id/mod.test.ts
> +    expect(check('0')).toBe(false);
d7fe3a5589b4607d2869f3703a98e406dc612aef で対応しました.

2024-04-05 14:44 UTC, MikuroXina approved these changes

2024-04-05 14:47 UTC, MikuroXina commented on pkg/accounts/model/account.ts
> +      if (!/^[a-zA-Z](?:.*[a-zA-Z0-9])?$/.test(label)) {
この修正だとドメイン名の `-` が末尾に含まれるケースで間違って通過しそうです. `@name@example-.com` などの場合でも期待通り拒否されるでしょうか?

2024-04-05 15:36 UTC, Nanai10a commented on pkg/accounts/model/account.ts
> +      if (!/^[a-zA-Z](?:.*[a-zA-Z0-9])?$/.test(label)) {
432126b371ea40dd0b357824e08c192a8a914093 でテストケースを追加しました.
また, それについては拒否されないので a57f612090ca7da8eb3cda0e756565290895a462 で対応しましたが, いかがでしょうか.

2024-04-05 15:37 UTC, MikuroXina approved these changes

2024-04-06 07:39 UTC, laminne approved these changes

2024-04-06 11:57 UTC, merged