feat: リノートの実装
pulsate-dev/pulsate pull request #264
Opened 2024-04-04 13:46 UTC by laminne

close #16 
## What does this PR do?
- `RenoteService`の実装
- `RenoteRoute`の定義とController,Handlerの実装

## Additional information
リノート可能か`renotable`の判定は最低限のものを除いてTimelineModuleに任せる方向で実装しています.

2024-04-06 08:43 UTC, MikuroXina requested changes

2024-04-06 08:43 UTC, MikuroXina commented on pkg/notes/adaptor/validator/schema.ts
> +  visibility: z.string().openapi({
```suggestion
  visibility: z
    .union([z.literal('public'), z.literal('home'), z.literal('followers')])
    .openapi({
```
他の API スキーマの定義では使われていないようですが, `z.union` を利用してみてはどうでしょうか? また [v0 の仕様の記述](https://www.notion.so/pulsate-dev/notes-note_id-renote-a82fd87ec850460183fe015501aaca31?pvs=4) では小文字になっていましたが, 大文字にする予定だったでしょうか?

2024-04-06 08:43 UTC, MikuroXina commented on pkg/notes/service/renote.test.ts
カバレッジを見るに以下のテストケースもあったほうがよさそうです.
- ID の生成に失敗するとき
- レポジトリでのリノートの発行に失敗するとき

2024-04-07 11:48 UTC, laminne commented
指摘箇所をすべて修正しました

2024-04-07 16:08 UTC, MikuroXina approved these changes

2024-04-07 16:08 UTC, merged