feat: use hono rpc mode in intermodule interfaces
pulsate-dev/pulsate pull request #324
Opened 2024-04-29 11:08 UTC by laminne

## What does this PR do?
- Hono RPCモードをIntermoduleの`AccountModule`クラスで利用するように

## Additional information
ToDo: コンストラクタ内でHono Clientを初期化する方法を探す  
ToDo: `AccountModule.fetchAccountByID`の実装を考える

2024-04-29 12:07 UTC, MikuroXina commented on pkg/intermodule/account.ts
> +  );
ここで 1 つにまとめているようですが, intermodule 側が各モジュールの詳細を触るのは責務を超えているかと思います. `pkg/accounts/mod.ts` のほうで, 各ハンドラの型情報をまとめた `AccountHandlerType` のような型を export してみてはどうでしょうか?

2024-04-29 12:33 UTC, laminne commented on pkg/intermodule/account.ts
> +  );
そうしてみます

2024-04-29 22:45 UTC, MikuroXina requested changes

2024-04-29 22:45 UTC, MikuroXina commented on pkg/accounts/mod.ts
> +export const CreateAccountHandler = accounts.openapi(
これらは export しなくてもよいのでは? `GetAccountHandler` も同じです
```suggestion
const CreateAccountHandler = accounts.openapi(
```

2024-04-29 22:45 UTC, MikuroXina commented on pkg/intermodule/account.ts
> +      param: { name: name },
```suggestion
      param: { name },
```
同名のキーとバリューなので略記できるかと

2024-05-01 13:40 UTC, MikuroXina commented on pkg/accounts/mod.ts
> +export const CreateAccountHandler = accounts.openapi(
`GetAccountHandler` の export は残ったままになっているので, まだ解決していないと思います. a80c61f は `const CreateAccountHandler` を除去したりする変更になっているようですが, このレビュー項目への対応を意図したものでしょうか?

2024-05-01 13:43 UTC, laminne commented on pkg/accounts/mod.ts
> +export const CreateAccountHandler = accounts.openapi(
> GetAccountHandler の export は残ったままになっているので, まだ解決していないと思います. 

消すの忘れてました

> https://github.com/pulsate-dev/pulsate/commit/a80c61fc462e6df1211daa5d223b95c6e9674a00 は const CreateAccountHandler を除去したりする変更になっているようですが, このレビュー項目への対応を意図したものでしょうか?

CreateAccountHandlerは現状どこからも参照されていないので削除しました.

2024-05-01 14:00 UTC, MikuroXina approved these changes

2024-05-01 15:19 UTC, merged