fix(notes/repository/BookmarkRepository): BookmarkRepositoryの型定義およびダミー実装の修正
pulsate-dev/pulsate pull request #325
Opened 2024-04-29 13:28 UTC by Allianaab2m

## What does this PR do?

BookmarkRepositoryにおけるcreate, findByID, deleteByIDが

- Bookmarkされた投稿のID(noteID)
- BookmarkしたアカウントのID(accountID)

を受け取り，処理するように修正しました．

2024-04-29 13:46 UTC, laminne requested changes

2024-04-29 13:46 UTC, laminne commented on pkg/notes/adaptor/repository/dummy.ts
> +  }): `${ID<NoteID>}_${ID<AccountID>}` {
文字列連結するよりかはタプルを使ったほうがまだ良さそう  
(後で分離できる必要が出てくる可能性があるので

普通にもう新しいIDを振っても良いとは思う
```ts
  }): [ID<NoteID>,ID<AccountID>] {
```

2024-04-29 13:52 UTC, Allianaab2m commented on pkg/notes/adaptor/repository/dummy.ts
> +  }): `${ID<NoteID>}_${ID<AccountID>}` {
bookmarksがMapで，Keyにオブジェクトを使うとgetが正しい結果を返さないんですよね...
それで無理やりstringにしてます

2024-05-02 01:11 UTC, Allianaab2m commented on pkg/notes/adaptor/repository/dummy.ts
> +  }): `${ID<NoteID>}_${ID<AccountID>}` {
`85d6ce2`でタプルをIDとして使用するように修正しました．

2024-05-02 01:51 UTC, laminne approved these changes

2024-05-02 01:58 UTC, merged