feat(notes/service): implement Create, Delete, FetchBookmarkService
pulsate-dev/pulsate pull request #334
Opened 2024-05-02 07:41 UTC by Allianaab2m

## What does this PR do?

- Bookmarkを作成するCreateBookmarkServiceの実装
- Bookmarkを削除するDeleteBookmarkServiceの実装
- Bookmarkを取得するFetchBookmarkServiceの実装

2024-05-02 13:11 UTC, laminne requested changes

2024-05-02 13:11 UTC, laminne commented on pkg/notes/service/fetchBookmark.test.ts
IDはモデルに関わらずユニークなのでこのテストは違法かも

2024-05-03 08:15 UTC, Allianaab2m commented on pkg/notes/service/fetchBookmark.test.ts
`b61be0a`で修正しました．

2024-05-04 08:25 UTC, m1sk9 requested changes
@laminne の指摘箇所以外では特にありません

2024-05-04 08:25 UTC, m1sk9 approved these changes
間違えました

2024-05-04 12:38 UTC, laminne approved these changes

2024-05-04 12:38 UTC, merged