fix(notes/bookmark): return target note model
pulsate-dev/pulsate pull request #391
Opened 2024-05-27 10:53 UTC by Allianaab2m

## What does this PR do?
- `BookmarkController.createBookmark`メソッドがNoteモデルを返すように変更
- `CreateBookmarkService`がコンストラクタにNoteRepositoryを要求するよう変更
- `CreateBookmarkService.handle`メソッドにブックマーク対象ノートが見つからなかったときの処理を追加
  - 追加した処理に対応するテストコードの追加

2024-05-27 11:56 UTC, MikuroXina requested changes

2024-05-27 11:56 UTC, MikuroXina commented on pkg/notes/service/createBookmark.ts
> +    return Result.ok(Option.unwrap(note));
`bookmarkRepository.create` が返すエラーが破棄されてしまっていそうです. `Result.map` で成功時に `note` が反映されるようにしてみてはどうでしょうか.
```suggestion
    const creation = await this.bookmarkRepository.create({ noteID, accountID });

    return Result.map(() => Option.unwrap(note))(creation);
```

2024-05-28 04:23 UTC, Allianaab2m commented on pkg/notes/service/createBookmark.ts
> +    return Result.ok(Option.unwrap(note));
`8efaf40`で修正しました．

2024-05-28 04:45 UTC, MikuroXina approved these changes

2024-05-28 04:49 UTC, merged