feat(notes): implement bookmark API handler
pulsate-dev/pulsate pull request #400
Opened 2024-05-30 00:23 UTC by Allianaab2m

## What does this PR do?

Bookmark APIのハンドラーを追加しました．

2024-05-30 00:37 UTC, laminne requested changes

2024-05-30 00:37 UTC, laminne commented on pkg/notes/mod.ts
> +  const { id: accountID } = c.req.valid('json');
accountIDはtokenから取得できる仕組みになる(はず)なのでbodyから取らなくても良いと思います(tokenの要求はもう少し先になりそうなのでtodoにでもしておいてほしいです)

2024-05-31 04:18 UTC, Allianaab2m commented on pkg/notes/mod.ts
> +  const { id: accountID } = c.req.valid('json');
https://github.com/pulsate-dev/pulsate/pull/400/commits/fa93ae73dfe411ef5d28a9c5bd9e4ef624008174 でToDoとしました．
この変更で動作しなくなっているので，別途Token対応のissueが必要かと思われます．

2024-05-31 04:21 UTC, laminne reviewed
(プログラム内のToDo)コメントは英語でお願いします 🙏🏻

2024-06-02 11:57 UTC, laminne approved these changes

2024-06-02 11:57 UTC, merged