feat: define List model
pulsate-dev/pulsate pull request #567
Opened 2024-07-18 14:09 UTC by laminne

## What does this PR do?
close #566 
- define list model
- list model tests

## Additional information

2024-07-18 14:54 UTC, MikuroXina requested changes

2024-07-18 14:54 UTC, MikuroXina commented on pkg/timeline/model/list.ts
> +  removeMember(memberId: AccountID) {
```suggestion
  addMember(memberId: AccountID): void {
    // ToDo: member limit
    if (this.memberIds.includes(memberId)) return;
    this.memberIds.push(memberId);
  }

  removeMember(memberId: AccountID): void {
```
戻り値型を明記してください

2024-07-18 14:54 UTC, MikuroXina commented on pkg/timeline/model/list.ts
> +    this.memberIds = args.memberIds;
メソッドの実装を見た限りだと, `args.memberIds` に重複した ID が含まれている場合に予期しない動作が発生しそうです. `AccountID[]` ではなく `Set<AccountID>` のようなデータ構造を活用してみてはどうでしょうか.

2024-07-19 05:22 UTC, m1sk9 commented on pkg/timeline/model/list.ts
> +  removeMember(memberId: AccountID) {
これ linter で縛りません?

2024-07-19 06:44 UTC, MikuroXina requested changes

2024-07-19 06:44 UTC, MikuroXina commented on pkg/timeline/model/list.ts
> +    if (this.memberIds.has(memberId)) return;
```suggestion
```
`Set` の `add` メソッドは既に要素が存在しているときに効果がないので, 判定は不要だと思います.

2024-07-19 06:44 UTC, MikuroXina commented on pkg/timeline/model/list.ts
> +  getMemberIds(): AccountID[] {
可変な配列を返していますが, これを変更しても `List` が保持するメンバー ID に影響しないことが分かりにくいです. ID の複製を返しているというドキュメントコメントを付けたほうが良さそうです.

2024-07-19 06:44 UTC, MikuroXina commented on pkg/timeline/model/list.ts
> +}
```suggestion
export type CreateListArgs = Readonly<{
  id: ListID;
  title: string;
  publicity: 'PUBLIC' | 'PRIVATE';
  ownerId: AccountID;
  memberIds: readonly AccountID[];
  createdAt: Date;
}>;
```
オブジェクト作成のために使うパラメータの意図であれば, 読み取ることしなしないので `readonly` を付けておきたいです.

2024-07-19 07:01 UTC, MikuroXina requested changes

2024-07-19 07:01 UTC, MikuroXina commented on pkg/timeline/model/list.test.ts
同じミスを予防するため, `CreateListArgs` の `memberIds` に重複 ID がある場合のテストケースがほしいです.

2024-07-19 07:07 UTC, MikuroXina approved these changes

2024-07-19 07:07 UTC, merged