refactor: intermodule, use direct function calls
pulsate-dev/pulsate pull request #585
Opened 2024-07-23 10:49 UTC by laminne

## What does this PR do?
close #549 
- IntermoduleパッケージをAPI経由ではなくController or Service経由で通信するように置き換え

## Additional information
基本的にControllerではなくServiceを使うようにしました
Controllerは依存が多く使うのが大変なため

2024-07-23 12:50 UTC, MikuroXina requested changes

2024-07-23 12:50 UTC, MikuroXina commented on pkg/intermodule/adaptor/account.ts
> +    return res;
```suggestion
    return res;
```
分岐に関わらず同じコードなので, err の分岐を書く必要はないかと.

2024-07-23 12:50 UTC, MikuroXina commented on pkg/intermodule/adaptor/account.ts
> +      res[1].map((v) => this.fetchService.fetchAccountByID(v.getTargetID())),
```suggestion
      Result.unwrap(res).map((v) => this.fetchService.fetchAccountByID(v.getTargetID())),
```
`Result` の内部構造を直接触らないようにしたいです. 他の `res[1]` をしているコードも同様です.

2024-07-23 12:50 UTC, MikuroXina commented on pkg/intermodule/interfaces/timeline.ts
interfaces 内のディレクトリのファイルで定義されている `interface` は `ModuleInterface` を末尾に付けていますが, ちょっと長くなりすぎる気がします. `Facade` のような接尾子/ディレクトリ名はどうでしょうか.

2024-07-23 15:48 UTC, MikuroXina requested changes

2024-07-23 15:48 UTC, MikuroXina commented on pkg/notes/mod.ts
> +
```suggestion
```
未使用コードはコメントとして残さないでください.

2024-07-23 15:48 UTC, MikuroXina commented on pkg/intermodule/adaptor/account.ts
他のモジュールが直接このアダプタ内の `AccountModule` に依存する形になっているようですが, これでは `AccountModuleFacade` という `interface` を用意した意味があまりにないです.
既にこの intermodule パッケージが中間層になっているので, `export class AccountModuleFacade` といった Facade パターンのクラスのみを公開したほうがよさそうです.
また production に応じた DI とその切り替えも intermodule 側で行ったほうがよさそうです.

2024-07-24 05:58 UTC, MikuroXina requested changes

2024-07-24 05:58 UTC, MikuroXina commented on pkg/intermodule/account.ts
`AccountModuleFacade` のメソッドの戻り値型がアカウントモジュールの型になっているものがありますが, このままだと型を記述するためにモジュール間の直接の `import` の記述を避けられなくなることがあります. このファイルから `export type from { Account } from "../accounts/model/accounts.js` のように再エクスポートしてやったほうがよさそうです.

2024-07-24 06:04 UTC, laminne commented on pkg/intermodule/account.ts
モジュール間依存を検出するlintルールとかあっても良さそう(biomeでそんなルールが書けるか不明ではあるが)

2024-07-24 06:40 UTC, MikuroXina requested changes

2024-07-24 06:40 UTC, MikuroXina commented on pkg/notes/mod.ts
> +);
こういった DI は notes モジュールではなく intermodule パッケージでやりたいです. Facade の構築の詳細な手段を notes が担うのは責務的におかしいですし, 今後も他のモジュールで同じコードが繰り返されることになります.

2024-07-24 06:40 UTC, MikuroXina commented on pkg/notes/service/fetch.test.ts
> +);
こちらも, テスト用の Facade のオブジェクトを intermodule 側で要するようにしたいです.

2024-07-24 08:08 UTC, MikuroXina approved these changes
`TimelineModuleFacade` に関しても同様の改善がほしいところですが, このリファクタに関してはこれで大丈夫だと思います.

2024-07-24 08:26 UTC, merged