feat: アカウントの複数一括取得の実装
pulsate-dev/pulsate pull request #588
Opened 2024-07-24 10:01 UTC by laminne

## What does this PR do?
- アカウントを複数取得する`fetchAccounts`の実装
  - 内部用のメソッドなのでAccountModuleFacadeから呼び出せるように

## Additional information

2024-07-24 10:05 UTC, MikuroXina commented on pkg/accounts/adaptor/repository/dummy.ts
> +    );
```suggestion
    const set = new Set<AccountID>(id);
    const accounts = Array.from(this.data).filter((a) =>
      set.has(a.getID()),
    );
```
毎回配列を線形探索するとパフォーマンスが少し気になるので, こうしてはどうでしょうか.

2024-07-24 10:31 UTC, MikuroXina requested changes

2024-07-24 10:31 UTC, MikuroXina commented on pkg/accounts/model/repository.ts
> +  findManyByID(id: AccountID[]): Promise<Result.Result<Error, Account[]>>;
```suggestion
  findManyByID(id: readonly AccountID[]): Promise<Result.Result<Error, Account[]>>;
```
この配列の引数は変更されることを意図していないでしょうから, `readonly` を付けておきたいです.

2024-07-24 16:46 UTC, m1sk9 approved these changes

2024-07-25 09:15 UTC, MikuroXina approved these changes

2024-07-25 14:59 UTC, merged