feat: 投稿にリアクションが付けられるようにする
pulsate-dev/pulsate pull request #619
Opened 2024-08-03 05:25 UTC by Allianaab2m

close #557

2024-08-03 09:24 UTC, MikuroXina requested changes

2024-08-03 09:24 UTC, MikuroXina commented on pkg/notes/adaptor/repository/dummy.ts
> +  private readonly reactions: Map<[NoteID, AccountID], Reaction>;
`[NoteID, AccountID]` のオブジェクトがキーだと, `Map` のメソッドで効率的に検索できないので効果が無いと思います. `Map<NoteID, Map<AccountID, Reaction>>` にしてみてもよさそうです.

2024-08-03 09:24 UTC, MikuroXina commented on pkg/notes/model/reaction.ts
> +  body: string;
`Reaction` もですが, この `body` というフィールドがリアクションにおいて何を意味するのかちょっと読み取りにくいです. Unicode 絵文字やカスタム絵文字の形式であれば, それをドキュメントコメントとして明記するか個別の型にしたいです.
もしそういった制約があるのであれば, 静的メソッド `new` でその検査を行うことになります.

2024-08-03 09:24 UTC, MikuroXina commented on pkg/notes/mod.ts
> +  return c.json(res[1], 200);
```suggestion
    return c.json({ error: Result.unwrap(res).message }, 400);
  }

  return c.json(Result.unwrap(res), 200);
```
`Result` の内部に直接アクセスしないほうがよいです. `unwrap` で取り出すか `mapOrElse` などの変換処理を使ってください.

2024-08-03 09:24 UTC, MikuroXina commented on pkg/notes/model/repository.ts
> +  findByAccountID(id: AccountID): Promise<Option.Option<Reaction[]>>;
```suggestion
  reactionsByAccount(id: AccountID): Promise<Reaction[]>;
```
この `findByAccountID` メソッドは `NoteID` を指定しないようになっていますが, それで取得してくる `Reaction[]` が何を意味するのかメソッド名から読み取れないです. 「そのアカウントによって行われたすべてのリアクション」という意味であれば, `Option` で包む必要は無さそうです.

2024-08-03 09:24 UTC, MikuroXina commented on pkg/notes/mod.ts
> +  }
このエラーの形式だとレスポンスコードを `400` にすべきか `404` にすべきか簡単に分からないので, `reactionController.create` の戻り値におけるエラー型を独自のものにしたほうがよさそうです.

2024-08-03 09:24 UTC, MikuroXina commented on pkg/notes/model/reaction.ts
> +  static new(arg: CreateReactionArgs) {
この静的メソッド `new` の戻り値型を明示してください.

2024-08-04 15:05 UTC, Allianaab2m commented on pkg/notes/adaptor/repository/dummy.ts
> +  private readonly reactions: Map<[NoteID, AccountID], Reaction>;
MapのKeyにNoteIDを使用すると，Map上ではKeyが一意となるために一つの投稿に1アカウントしかリアクションが追加できなくなるように思われます．
Prisma側では複合キーとして設定されているため，AccountIDとNoteIDを文字列結合して1つのIDとして扱うほうがいいでしょうか？

2024-08-04 15:25 UTC, Allianaab2m commented on pkg/notes/model/reaction.ts
> +  static new(arg: CreateReactionArgs) {
修正しました．(bd0bd81f3a6a2288d0169358df5a7b72e938eae7)

2024-08-04 15:25 UTC, Allianaab2m commented on pkg/notes/model/repository.ts
> +  findByAccountID(id: AccountID): Promise<Option.Option<Reaction[]>>;
修正しました．(689908c6005c4e543c193bed8a90c9f50201d86f)

2024-08-04 16:06 UTC, MikuroXina commented on pkg/notes/adaptor/repository/dummy.ts
> +  private readonly reactions: Map<[NoteID, AccountID], Reaction>;
確かにそのほうがよさそうですね. それでお願いできますか.

2024-08-05 10:32 UTC, MikuroXina requested changes

2024-08-05 10:32 UTC, MikuroXina commented on pkg/notes/adaptor/repository/dummy.ts
> +type NoteID_AccountID = string;
```suggestion
type CompositeKey = `${NoteID}_${AccountID}`;
```
こういうふうにテンプレートリテラル型として書いたほうがよさそうです.

2024-08-05 10:32 UTC, MikuroXina commented on pkg/notes/adaptor/controller/reaction.ts
> +      { code: 400 | 404; error: Error },
`400` や `404` といった HTTP レスポンスコードのような通信プロトコルに関する知識は, この `ReactionConrtoller` に有してほしくないです. エラーを HTTP レスポンスコードに変換するような処理は, Presenter などと呼ばれるユーザへ提示する内容を取り扱う別のアダプタで行いたいです.

2024-08-11 22:52 UTC, MikuroXina commented on pkg/notes/adaptor/presenter/reacton.ts
> +  code: 400 | 404;
並びから HTTP レスポンスコードであることはある程度予想が付くものの, この 400 や 404 はマジックナンバーになっています. この数値それぞれの意味を型やドキュメントコメントとして明記してはどうでしょうか.

2024-08-11 23:14 UTC, MikuroXina commented on pkg/notes/adaptor/presenter/reacton.ts
> +  code: 400 | 404; // 400: Bad Request / 404: Not Found
```suggestion
  /** 400: Bad Request / 404: Not Found */
  code: 400 | 404;
```
ドキュメントコメントは (1 行であれば) このように `/** ... */` と囲って記述してください.

2024-08-12 10:54 UTC, MikuroXina approved these changes

2024-08-12 10:56 UTC, merged