feat: ノートの複数取得メソッドをfetchServiceに追加
pulsate-dev/pulsate pull request #715
Opened 2024-09-20 09:12 UTC by laminne

## What does this PR do?
- fetchServiceにノートの複数取得メソッドを追加
- NoteRepositoryにも同様に追加

## Additional information
- 電車に乗りながら書いたのでミスがあるかもしれません.ちょっと入念に見てほしいかもしれないです

2024-09-20 09:56 UTC, MikuroXina requested changes

2024-09-20 09:56 UTC, MikuroXina commented on pkg/notes/model/repository.ts
> +  findManyByIDs(ids: NoteID[]): Promise<Result.Result<Error, Note[]>>;
このメソッドの戻り値に関するドキュメントコメントが欲しいです. 戻り値となる `Note` の配列は作成時刻でソートされていることを保証するのでしょうか? それとも何も保証されないのでしょうか?

2024-09-21 04:29 UTC, m1sk9 requested changes

2024-09-21 04:29 UTC, m1sk9 commented on pkg/notes/model/repository.ts
> +   * @param ids
引数の説明を加えてください

2024-09-22 03:02 UTC, m1sk9 approved these changes

2024-09-22 06:39 UTC, MikuroXina requested changes

2024-09-22 06:39 UTC, MikuroXina commented on pkg/notes/model/repository.ts
> +   * @param ids ID of the NOTE to be obtained
`ids` 内の ID に重複がある場合はソートされている戻り値と配列では内でどのように扱われますか? 重複した分は無視されますか? それとも重複した分だけ同じノートが増えますか?

2024-09-22 07:12 UTC, laminne commented on pkg/notes/model/repository.ts
> +   * @param ids ID of the NOTE to be obtained
今の実装だと(InMemoryの場合で)重複した分が無視されないようになっていますが、Prismaの方でどうなるのかがわからないので重複した分は無視するようにします

2024-09-22 07:18 UTC, laminne commented on pkg/notes/model/repository.ts
> +   * @param ids ID of the NOTE to be obtained
無視するようにしました
[`f489b11`](https://github.com/pulsate-dev/pulsate/pull/715/commits/f489b119fe1408293cd8e67cd1ba95e0a610df9b)

2024-09-22 07:25 UTC, MikuroXina approved these changes

2024-09-22 07:25 UTC, merged