feat: Listタイムラインのノートを取得できるように
pulsate-dev/pulsate pull request #733
Opened 2024-09-30 14:56 UTC by laminne

## What does this PR do?
close #562 
- ListTimelineServiceの実装
- controller,handler定義

## Additional information
controllerの実装がだいぶ非効率になっている気がしています(実際に動かないとわからないかもしれないですが...)

2024-09-30 15:25 UTC, MikuroXina requested changes

2024-09-30 15:25 UTC, MikuroXina commented on pkg/timeline/adaptor/controller/timeline.ts
> +    ]);
概念的に `readonly` で渡してよいはずですが, モジュール表面やサービスの部分だけ `readonly` が付いていなくてこうせざるを得ないのが気になります. アカウントモジュール側の定義を修正しておきたいです.

2024-09-30 15:25 UTC, MikuroXina commented on pkg/timeline/adaptor/controller/timeline.ts
> +    Result.unwrap(noteAuthorRes).map((v) => noteAuthorMap.set(v.getID(), v));
```suggestion
    for (const author of Result.unwrap(noteAuthorRes)) {
      noteAuthorMap.set(author.getID(), author);
    }
```
副作用があって戻り値が無い処理は `map` ではなく `for-of` で処理してほしいです.

2024-09-30 15:25 UTC, MikuroXina commented on pkg/timeline/adaptor/controller/timeline.ts
> +    for await (const v of notes) {
```suggestion
    for (const v of notes) {
```
`notes` は `AsyncIterator` なオブジェクトではなく配列なので, `for await` にする意味は無いと思います.

2024-09-30 15:25 UTC, MikuroXina commented on pkg/timeline/service/list.test.ts
> +  });
このテストケースですが, ソート処理の想定が安定ソートなのか不安定ソートなのかがテスト不足かと思います. つまり, 作成時刻が同じでも内容の異なるノートは存在し得るのですが, その場合に元々入っていたデータの順序を保つようにするのか, その順序は実行の度に変化してもよいのかが気になります.

2024-09-30 15:25 UTC, MikuroXina commented on pkg/timeline/service/list.ts
> +    return Result.ok(Result.unwrap(notesRes));
```suggestion
    return notesRes;
```
エラーをそのまま報告する or 取り出して詰め直す処理は, そのまま `return` するのと同じです.

2024-09-30 15:29 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    ]);
これは別にIssueを立てて解決しようと思います

2024-10-01 05:26 UTC, MikuroXina approved these changes

2024-10-01 05:27 UTC, MikuroXina commented on pkg/timeline/adaptor/controller/timeline.ts
> +    ]);
今のうちに Issue を立てるか TODO コメントを残すことを推奨します.

2024-10-01 05:28 UTC, laminne commented on pkg/timeline/adaptor/controller/timeline.ts
> +    ]);
#736 を立てました

2024-10-01 06:16 UTC, merged