feat: push note to author's home timeline
pulsate-dev/pulsate pull request #782
Opened 2024-10-20 15:25 UTC by laminne

close #781 
## What does this PR do?
- 投稿した本人のホームタイムラインにノートを配信するようにしました
  - Caramelで正しく動作することを確認済み(投稿後のタイムライン自動更新も含め)

2024-10-20 15:30 UTC, MikuroXina requested changes

2024-10-20 15:30 UTC, MikuroXina commented on pkg/timeline/service/push.ts
> +    });
特殊なフォロワーの値を用意するのは危険なので, 素直に `timelineNotesCacheRepository.addNotesToHomeTimeline` の呼び出しを 1 回分増やしてみてはどうでしょうか.

2024-10-21 05:30 UTC, laminne commented on pkg/timeline/service/push.ts
> +    });
そうしておきます

2024-10-21 08:12 UTC, MikuroXina approved these changes

2024-10-21 08:12 UTC, merged