feat: Added cache retention limit to list/home timeline
pulsate-dev/pulsate pull request #806
Opened 2024-11-01 01:57 UTC by laminne

close #801 
## What does this PR do?
- リスト/ホームタイムラインのキャッシュを300件までに制限するように
- ノートのソートに使う要素をCreatedAtからIDに

## Additional information

2024-11-01 08:47 UTC, MikuroXina requested changes

2024-11-01 08:47 UTC, MikuroXina commented on pkg/timeline/adaptor/repository/dummyCache.ts
> +    return Result.ok(fetched.sort((a, b) => Number(BigInt(b) - BigInt(a))));
`NoteID` が数字のみであることに依存するのは, 内部表現を直接触るコードがあちらこちらに分散してよくないと思います. `NoteID` モデルの定義のほうで, 2 つの `NoteID` を比較する関数を提供するようにしてほしいです.

2024-11-01 08:47 UTC, MikuroXina commented on pkg/timeline/service/push.ts
> +     * @description Limit of timeline cache
```suggestion
     * @description Limit length of timeline caches
```
単位が不明瞭なので, キャッシュのエントリ数であることを説明に書いてほしいです.

2024-11-01 08:47 UTC, MikuroXina commented on pkg/timeline/service/push.ts
> +        if (!oldestNote) {
タイムラインの長さが制限より 2 つ以上多くなることもありそうですが, この仕様/実装で大丈夫でしょうか?

2024-11-01 08:47 UTC, MikuroXina commented on pkg/timeline/service/push.ts
> +      const unwrappedTimeline = Result.unwrap(timeline);
```suggestion
      const timelineRes = await this.timelineNotesCacheRepository.getHomeTimeline(
        timelineID as AccountID,
      );
      if (Result.isErr(timelineRes)) {
        return timelineRes;
      }
      const timeline = Result.unwrap(timelineRes);
```
`Result` のほうを `timelineRes` にして, `unwrap` 後のほうを `timeline` にすることを推奨します.

2024-11-01 11:23 UTC, laminne commented
タイムラインへのノート配信は1つづつ行うので複数一気に追加することを想定することはしていません

2024-11-01 16:46 UTC, MikuroXina requested changes

2024-11-01 16:46 UTC, MikuroXina commented on pkg/id/mod.ts
> +export const compareID = <T>(a: ID<T>, b: ID<T>) =>
```suggestion
export const compareID = <T>(a: ID<T>, b: ID<T>): number =>
```
戻り値型を明示してください.

2024-11-02 02:18 UTC, MikuroXina approved these changes

2024-11-02 02:18 UTC, merged