feat: アカウントのヘッダー/アバター画像の設定、設定解除ができるように
pulsate-dev/pulsate pull request #823
Opened 2024-11-12 15:12 UTC by laminne

close #809 
## What does this PR do?
- ヘッダーとアバター画像の設定、設定解除ができるように
- アカウント取得時にヘッダー・アバター画像を(あれば)返すように
- マイグレーションの追加(AccountHeader/AccountAvatar モデル)
- MediaModuleFacadeの定義と実装
- Service実装とDIシンボルの定義
- APIの実装

## Additional information

2024-11-12 22:50 UTC, MikuroXina requested changes

2024-11-12 22:50 UTC, MikuroXina commented on pkg/accounts/adaptor/controller/account.ts
> +      : '';
```suggestion
    const avatar = Result.mapOr('')((avatar) => avatar.getUrl())(avatarRes);
```
[`mapOr`](https://mikuroxina.github.io/mini-fn/functions/Result.mapOr.html) を使ったほうがよいかと思います. 他の三項演算子と `unwrap` で書いているところも同様です.

2024-11-12 22:50 UTC, MikuroXina commented on pkg/accounts/adaptor/controller/account.ts
> +    return Result.ok(undefined);
```suggestion
    return res;
```
`res` は `Result<Error, void>` 型なので, そのまま返してよいと思います.
ヘッダーの方と `unset` する方の処理も同様です.

2024-11-12 22:50 UTC, MikuroXina commented on pkg/accounts/adaptor/repository/dummy/account.ts
> +  }
同じ `AccountID` を持つ異なる `Account` 型のオブジェクトが混ざる可能性があるので, `Set<Account>` ではなく `Map<AccountID, Account>` を使ったほうがよいかと思います.

2024-11-12 22:50 UTC, MikuroXina commented on pkg/accounts/model/repository.ts
> +  ): Promise<Result.Result<Error, void>>;
この `create` の意味論ですが, そのアカウントにアバターが既に存在する状態で再び `create` を呼び出した場合は上書きされますか? それともエラーになりますか? ドキュメントコメントとして明示しておきたいです.

2024-11-12 22:50 UTC, MikuroXina commented on pkg/drive/service/fetch.ts
> +  async fetchMediaByID(mediumID: MediumID) {
メソッドの戻り値型を明示してください.

2024-11-13 01:42 UTC, laminne commented on pkg/accounts/adaptor/repository/dummy/account.ts
> +  }
このPRでは対応せず別のIssueに分離することにしました

2024-11-13 01:52 UTC, MikuroXina commented on pkg/accounts/adaptor/controller/account.ts
> +    )(headerRes);
```suggestion
    const avatar = Result.mapOr('')(getMediumUrl)(avatarRes);
    const header = Result.mapOr('')(getMediumUrl)(headerRes);
```
任意ですが, `getUrl` を呼び出す `getMediumUrl` 関数を `Medium` の定義ファイルにでも用意しておくと, 少し簡潔に書けると思います.

2024-11-13 02:22 UTC, laminne commented on pkg/accounts/adaptor/controller/account.ts
> +    )(headerRes);
これは別PRで対応しようと思います

2024-11-13 02:25 UTC, MikuroXina approved these changes

2024-11-13 02:25 UTC, merged