feat: HomeTimelineでafterIDを使ってページネーションできるように
pulsate-dev/pulsate pull request #871
Opened 2024-12-08 07:16 UTC by laminne

## What does this PR do?
- HomeTimelineでそれ以降(新しい)の投稿を取得できるように

## Additional information

2024-12-08 14:06 UTC, MikuroXina requested changes

2024-12-08 14:06 UTC, MikuroXina commented on pkg/timeline/adaptor/repository/dummy.test.ts
`before` と `after` を同時に指定したらエラーになるというテストケースがあったほうがよさそうです. 仕様をテストで表現したいです.

2024-12-08 14:06 UTC, MikuroXina commented on pkg/timeline/model/repository.ts
>  }
任意ですが, モデルはアダプタで扱いやすくするよりコントローラーの処理を厳格に表現したいので, このように定義する手もあります.
```ts
export interface FetchAccountTimelineFilter {
  // ...
  noNsfw: boolean;
  cursor?: Cursor;
}

export interface FilterCursor {
    type: "before" | "after;
    id: NoteID;
}
```

2024-12-09 05:10 UTC, laminne commented on pkg/timeline/model/repository.ts
>  }
カーソルページネーションの実装箇所は他にもあるので,別Issueで対応しようと思います

2024-12-09 11:33 UTC, MikuroXina requested changes

2024-12-09 11:33 UTC, MikuroXina commented on pkg/timeline/adaptor/repository/dummy.ts
> +      console.log(filtered.slice(beforeIndex).map((v) => v.getID()));
```suggestion
```
こういう状況が分からないログは除去したいです.

2024-12-10 13:16 UTC, MikuroXina approved these changes

2024-12-11 16:08 UTC, merged