feat: define Notification model
pulsate-dev/pulsate pull request #876
Opened 2024-12-10 04:47 UTC by laminne

close #874 

## What does this PR do?
- Notificationモデルの定義
  - Announceモデルはv0.1では取り敢えずやらないことにします

## Additional information

2024-12-10 13:22 UTC, MikuroXina requested changes

2024-12-10 13:22 UTC, MikuroXina commented on pkg/notification/model/notification.ts
> +  private readAt: Option.Option<Date>;
既読かどうかは `readAt` が `some` かどうかで判定できそうですが, `isRead` に分けてあるのはなぜでしょうか?

2024-12-10 13:22 UTC, MikuroXina commented on pkg/notification/model/notification.ts
> +    this.readAt = Option.some(new Date());
ここで `new Date()` を呼び出してしまうとモデルとして純粋でなくなるので, 時刻は引数で受け取るようにしたほうがよいかと思います.

2024-12-11 14:46 UTC, laminne commented on pkg/notification/model/notification.ts
> +  private readAt: Option.Option<Date>;
getIsRead関数を実装するためのフラグとして作ったつもりですが、Optionで判定できることに今更気づきました

2024-12-11 16:18 UTC, MikuroXina requested changes

2024-12-11 16:18 UTC, MikuroXina commented on pkg/notification/model/notification.ts
> +  }
この仕様だと `none` を設定できないので未読に戻せないと思うのですが, 想定通りですか? それとドキュメントコメントですが, `true` にするわけではなくなったので更新お願いします.

2024-12-12 02:53 UTC, laminne commented on pkg/notification/model/notification.ts
> +  }
未読に戻せないのは想定通りです.
ドキュメントの更新をしておきます

2024-12-14 15:20 UTC, MikuroXina commented on pkg/notification/model/notification.ts
> +   * NOTE: Once a message has been read, it cannot be marked as unread.
```suggestion
   * Set time when message read
   *
   * NOTE: Once a message has been read, it cannot be marked as unread.
```
改行のための `\` なのでしたら, そうせず段落を分けたほうがよいかと思います.

2024-12-15 10:47 UTC, MikuroXina approved these changes

2024-12-15 10:47 UTC, merged